### PR TITLE
60 add some basic visualisation for analysis

### PR DESCRIPTION
**Pull request by yaseminbridges**
Implementation of graph visualisation (bar plot) for summary rank statistics

### CODE REVIEW

**Comment by yaseminbridges** [comment]
Key changes:

- Parsing PhEval gene and variant tsv results into dataclasses and accessing these during analysis rather than dataframe values
- Implementation of plot visualisation of rank statistics, including stacked bar charts and cumulative and non-cumulative bar plots

**Review by julesjacobsen — APPROVED** [review]
Looks sane enough. Rather large to judge this as a whole, but the output looks good.

**Comment by julesjacobsen** [comment]
Are you done with the changes now? If so, best merge this sooner rather than later.

**Comment by yaseminbridges** [comment]
> Are you done with the changes now? If so, best merge this sooner rather than later.

Yes, I don't plan on making any more changes to this PR now. Any other additions I want to do separately as this is already large enough

**Pull request merged**
